# Generated by Django 5.1.3 on 2025-01-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estado_respuesta',
            field=models.CharField(choices=[('Contestada', 'Contestada'), ('No contestada', 'No contestada'), ('En proceso', 'En proceso')], default='No contestada', max_length=100),
        ),
    ]
