# Generated by Django 5.1.3 on 2024-12-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('adquirido', 'Adquirido'), ('jugado', 'Jugado')], default='adquirido', max_length=50)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=10)),
                ('cuil', models.CharField(max_length=10)),
                ('imagen', models.ImageField(blank=True, default='defecto/defecto.png', null=True, upload_to='usuario/%Y/%m/%d')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
